### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Eco-Gaming** [Joristdh/iSki2GPX#2]
Hey, I just noticed your repo doesn't have a license, which technically means no one is allowed to fork and modify it.
It is very easy to add a license using GitHub (see [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)), I would recommend GPLv3 or MIT.

For more info, see this website: https://choosealicense.com/.

**Comment by Joristdh** [comment]
To be honest, I never really expected other to contribute to this project. However, you are correct, so I've added a GPLv3 license.
